### PR TITLE
upgrade snappy-java jar to 1.1.10.1

### PR DESCRIPTION
**Pull request by rhuffy**
#419 was not sufficient to upgrade snappy-java. We also need to update the jar file included in the repo.

### CODE REVIEW

**Comment by rhuffy** [comment]
```
$ shasum -a 256 lib/snappy-java-1.1.10.1.jar 
5a6224cb7f946f5a7db9c77e86af6ccd43ba5ae38b1a15bea23113cc83f8fabd  lib/snappy-java-1.1.10.1.jar
```

**Comment by tpetracca** [comment]
You'll also want to update hte license: https://github.com/palantir/cassandra/blob/palantir-cassandra-2.2.18/lib/licenses/snappy-java-1.1.8.4.txt

There's a good chance it isn't any different (in which case it will at least update the file name)

**Comment by rhuffy** [comment]
License content is the same, just updated the filename

**Review by tpetracca — APPROVED** [review]

**Comment by rhuffy** [comment]
```
shasum -a 1 lib/snappy-java-1.1.10.1.jar
4a1e1a22cba39145dfa20f2fef4e1ca38c8e02a1  lib/snappy-java-1.1.10.1.jar
```

This matches https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.1/snappy-java-1.1.10.1.jar.sha1

4a1e1a22cba39145dfa20f2fef4e1ca38c8e02a1

**Pull request merged**
